"""agenteval - evaluation harness for LLM systems and agents.

Scores systems against task suites and reports results with statistics that
refuse to overclaim: confidence intervals everywhere, INCONCLUSIVE verdicts
when evidence is thin, and corrections for multiple comparisons.

    from agenteval import ExactMatchGrader, evaluate, suite_from_records

    suite = suite_from_records("math", [
        {"id": "q1", "input": "2+2", "expected": "4"},
    ])
    run = evaluate(my_system, suite, ExactMatchGrader())
    print(run.pass_rate)

See https://github.com/Abdus-Sami01/agenteval for the full guide.
"""

from __future__ import annotations

import logging

from agenteval._version import __version__, __version_info__
from agenteval.agreement import (
    AgreementReport,
    JudgeValidation,
    cohens_kappa,
    krippendorff_alpha,
    percent_agreement,
    validate_judge,
)
from agenteval.cache import PredictionCache, prediction_key
from agenteval.calibration import (
    CalibrationReport,
    brier_score,
    brier_skill_score,
    calibration,
    log_loss,
    reliability_diagram_text,
)
from agenteval.compare import Comparison, compare, gate, regression_gate
from agenteval.contamination import (
    ContaminationHit,
    ContaminationReport,
    CorpusIndex,
    clean_suite,
    detect_contamination,
    find_duplicates,
    ngram_hashes,
)
from agenteval.cost import (
    BudgetExceeded,
    CostReport,
    CostTracker,
    cost_efficiency,
    estimate_tokens,
    token_cost,
)
from agenteval.exceptions import (
    AgentEvalError,
    BudgetExceededError,
    ConfigurationError,
    GraderError,
    PairedLengthError,
    StatisticsError,
    SuiteError,
    SuiteFormatError,
    UnknownGraderError,
)
from agenteval.graders import (
    CallableGrader,
    ContainsGrader,
    EditDistanceGrader,
    ExactMatchGrader,
    F1TokenGrader,
    Grader,
    GraderRegistry,
    JSONSchemaGrader,
    LLMJudgeGrader,
    NumericGrader,
    PredicateGrader,
    RangeGrader,
    RegexGrader,
    RubricGrader,
    SetGrader,
    StructuralGrader,
    WeightedGrader,
    normalize_text,
)
from agenteval.html import leaderboard_to_html, run_to_html, write_html
from agenteval.multiple import (
    MultipleComparisonReport,
    SystemMatrix,
    adjust,
    benjamini_hochberg,
    bonferroni,
    compare_all,
    holm_bonferroni,
)
from agenteval.progress import ProgressReporter, configure_logging
from agenteval.report import (
    failure_digest,
    leaderboard,
    leaderboard_tiers,
    run_to_dict,
    run_to_json,
    run_to_markdown,
    run_to_text,
    tag_breakdown,
)
from agenteval.resume import ResultStore, evaluate_resumable
from agenteval.runner import detect_git_sha, evaluate, evaluate_many, iter_evaluate, repeat_evaluate
from agenteval.sequential import (
    SequentialGate,
    SequentialRun,
    StoppingDecision,
    evaluate_sequential,
)
from agenteval.stability import (
    StabilityReport,
    TaskStability,
    analyze_stability,
    intraclass_correlation,
    required_repeats,
)
from agenteval.stats import (
    Interval,
    TestResult,
    bca_interval,
    bootstrap_interval,
    cliffs_delta,
    cohens_d,
    interpret_effect,
    mcnemar_test,
    mean,
    minimum_detectable_effect,
    paired_bootstrap_diff,
    permutation_test,
    required_sample_size,
    stdev,
    stratified_rates,
    wilson_interval,
)
from agenteval.suites import (
    load_csv,
    load_json,
    load_jsonl,
    load_suite,
    load_yaml,
    save_suite,
    suite_from_records,
    validate_suite,
)
from agenteval.types import (
    EvalRun,
    GateReport,
    GateResult,
    Outcome,
    RunMetadata,
    Score,
    Task,
    TaskResult,
    TaskSuite,
)

logging.getLogger("agenteval").addHandler(logging.NullHandler())

__all__ = [
    "adjust",
    "AgentEvalError",
    "AgreementReport",
    "analyze_stability",
    "bca_interval",
    "benjamini_hochberg",
    "bonferroni",
    "bootstrap_interval",
    "brier_score",
    "brier_skill_score",
    "BudgetExceeded",
    "BudgetExceededError",
    "calibration",
    "CalibrationReport",
    "CallableGrader",
    "clean_suite",
    "cliffs_delta",
    "cohens_d",
    "cohens_kappa",
    "compare",
    "compare_all",
    "Comparison",
    "ConfigurationError",
    "configure_logging",
    "ContainsGrader",
    "ContaminationHit",
    "ContaminationReport",
    "CorpusIndex",
    "cost_efficiency",
    "CostReport",
    "CostTracker",
    "detect_contamination",
    "detect_git_sha",
    "EditDistanceGrader",
    "estimate_tokens",
    "EvalRun",
    "evaluate",
    "evaluate_many",
    "evaluate_resumable",
    "evaluate_sequential",
    "ExactMatchGrader",
    "F1TokenGrader",
    "failure_digest",
    "find_duplicates",
    "gate",
    "GateReport",
    "GateResult",
    "Grader",
    "GraderError",
    "GraderRegistry",
    "holm_bonferroni",
    "interpret_effect",
    "Interval",
    "intraclass_correlation",
    "iter_evaluate",
    "JSONSchemaGrader",
    "JudgeValidation",
    "krippendorff_alpha",
    "leaderboard",
    "leaderboard_tiers",
    "leaderboard_to_html",
    "LLMJudgeGrader",
    "load_csv",
    "load_json",
    "load_jsonl",
    "load_suite",
    "load_yaml",
    "log_loss",
    "mcnemar_test",
    "mean",
    "minimum_detectable_effect",
    "MultipleComparisonReport",
    "ngram_hashes",
    "normalize_text",
    "NumericGrader",
    "Outcome",
    "paired_bootstrap_diff",
    "PairedLengthError",
    "percent_agreement",
    "permutation_test",
    "PredicateGrader",
    "prediction_key",
    "PredictionCache",
    "ProgressReporter",
    "RangeGrader",
    "RegexGrader",
    "regression_gate",
    "reliability_diagram_text",
    "repeat_evaluate",
    "required_repeats",
    "required_sample_size",
    "ResultStore",
    "RubricGrader",
    "run_to_dict",
    "run_to_html",
    "run_to_json",
    "run_to_markdown",
    "run_to_text",
    "RunMetadata",
    "save_suite",
    "Score",
    "SequentialGate",
    "SequentialRun",
    "SetGrader",
    "StabilityReport",
    "StatisticsError",
    "stdev",
    "StoppingDecision",
    "stratified_rates",
    "StructuralGrader",
    "suite_from_records",
    "SuiteError",
    "SuiteFormatError",
    "SystemMatrix",
    "tag_breakdown",
    "Task",
    "TaskResult",
    "TaskStability",
    "TaskSuite",
    "TestResult",
    "token_cost",
    "UnknownGraderError",
    "validate_judge",
    "validate_suite",
    "__version__",
    "__version_info__",
    "WeightedGrader",
    "wilson_interval",
    "write_html",
]
